### ISSUE TITLE
librdkafka static linking issue 

### ISSUE THREAD

**Issue by pranav-bhatt** [fede1024/rust-rdkafka#292]
Hi! In my CI environment when I try to run `cargo build` using "x86_64-unknown-linux-musl" as the target(both in stable and nightly), I get a librdkafka compile error:

```
Building and linking librdkafka statically
Running command: "cp -a librdkafka/. /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/rdkafka-sys-6a10e15fa8f0286a/out" in dir: .
Running command: "/home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/rdkafka-sys-6a10e15fa8f0286a/out/configure --disable-ssl --disable-gssapi --disable-zstd --disable-lz4-ext" in dir: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/rdkafka-sys-6a10e15fa8f0286a/out
Running command: "make libs" in dir: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/rdkafka-sys-6a10e15fa8f0286a/out
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata.crc_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(deflate.o): relocation R_X86_64_32S against hidden symbol `zcalloc' can not be used when making a shared object
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(inflate.o): relocation R_X86_64_32S against hidden symbol `zcalloc' can not be used when making a shared object
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(inftrees.o): relocation R_X86_64_32S against `.rodata.lbase.2763' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(trees.o): relocation R_X86_64_32S against `.rodata.static_l_desc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(zutil.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/runner/work/sdk-rust/sdk-rust/target/x86_64-unknown-linux-musl/debug/build/libz-sys-996a19991a608422/out/build/libz.a(inffast.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[1]: *** [librdkafka.so.1] Error 1
make: *** [libs] Error 2
thread 'main' panicked at 'Command failed with error code 2', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-sys-1.3.1/build.rs:34:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is my CI workflow file:
```
name: Master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests on ${{ matrix.toolchain }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - wasm32-unknown-unknown
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update
      if: matrix.target == 'x86_64-unknown-linux-musl'
    - run: sudo apt-get install -y musl musl-dev musl-tools
      if: matrix.target == 'x86_64-unknown-linux-musl'
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ matrix.toolchain }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target: ${{ matrix.target }}
        override: true

    # If glibc, compile and test all
    - uses: actions-rs/cargo@v1
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      with:
        command: build
        toolchain: ${{ matrix.toolchain }}
        args: --target ${{ matrix.target }} --workspace
    - uses: actions-rs/cargo@v1
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      with:
        command: test
        toolchain: ${{ matrix.toolchain }}
        args: --target ${{ matrix.target }} --workspace

    # If musl, compile and test all
    - uses: actions-rs/cargo@v1
      if: matrix.target == 'x86_64-unknown-linux-musl'
      with:
        command: build
        toolchain: ${{ matrix.toolchain }}
        args: --target ${{ matrix.target }} --all
    - uses: actions-rs/cargo@v1
      if: matrix.target == 'x86_64-unknown-linux-musl'
      with:
        command: test
        toolchain: ${{ matrix.toolchain }}
        args: --target ${{ matrix.target }} --all

```
The weird thing is that it works perfectly fine locally! I even added `- run: sudo wget https://zlib.net/zlib-1.2.11.tar.gz && tar -xvzf zlib-1.2.11.tar.gz && cd zlib-1.2.11 && ./configure --prefix=/usr/local/zlib --enable-shared && sudo make install` as a last hurrah. Any ideas where this might be messing up, or something else I might need to add? Thanks!
