### ISSUE TITLE
Production error MessageTimedOut when upgrade from 0.31 to 0.33

### ISSUE THREAD

**Issue by DreamyDelight** [fede1024/rust-rdkafka#601]
Hi!

In my case, that is constantly working fine. but I got some errors such as " Failed to produce Kafka message: Message production error: MessageTimedOut (Local: Message timed out)" When  I upgraded it from 0.31 to 0.33, I can't figure out what the problem it is.

So, Am I missing some important thing at version 0.33? Here is the snap code

```rust
use rdkafka::config::ClientConfig;
use rdkafka::producer::{FutureProducer, FutureRecord};
use std::error::Error;
use std::time::Duration;

pub async fn produce(brokers: &str, topic_name: &str, message: &str) -> Result<(i32, i64),  Box<dyn Error>> {
  let producer: &FutureProducer = &ClientConfig::new()
    .set("bootstrap.servers", brokers)
    .set("message.timeout.ms", "5000")
    .create()
    .expect("Producer creation error");

  let res: (i32, i64) = match producer.send(
  FutureRecord::to(topic_name)
    .payload(message)
    .key("simple-key"),
    Duration::from_secs(0),
  ).await {
    Ok(v) => v,
    Err(err) => return Err(Box::new(err.0)),
  };

  Ok(res)
}

```

**Comment by davidblewett** [comment]
I tested your sample against `rdkafka = 0.31.0` and `rdkafka = 0.33.2` and was not able to reproduce an error. Are you sure your Kafka cluster is running on the expected IP and port?

**Comment by DreamyDelight** [comment]
@davidblewett I'm exactly the Kafka cluster is always working because the two diff containers running with the same config that the 0.31 version container to be working fine, and the other 0.33 container failed with  " Failed to produce Kafka message: Message production error: MessageTimedOut (Local: Message timed out)".

**Comment by DreamyDelight** [comment]
I'm confused about it the `rdkafka = 0.31.0` and `rdkafka = 0.33.2` always got the error "MessageTimedOut"
so..., is the error maybe around the container?

**Comment by davidblewett** [comment]
I created a barebones self-contained repo here: https://github.com/davidblewett/timeout_test . Can you try to reproduce with this in your environment? Just change the pin of `rdkafka` in `Cargo.toml` and run `cargo run`.

**Comment by DreamyDelight** [comment]
> I created a barebones self-contained repo here: https://github.com/davidblewett/timeout_test . Can you try to reproduce with this in your environment? Just change the pin of `rdkafka` in `Cargo.toml` and run `cargo run`.

I'm testing that it's working in my environment with your repo https://github.com/davidblewett/timeout_test, It seems so curious to me. here is my `Cargo.toml` dep

```toml
[dependencies]
redis = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
env_logger = "0.10"
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
http = "0.2"
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
regex = "1.4"
rand = "0.8"
rdkafka = "0.31"
anyhow = "1"
```

Maybe some dependencies conflict make this error?
